左側メニューの多言語対応
hiroyuki-ichikawa/fujicity_covid19 pull request #37
Opened 2021-02-12 13:38 UTC by jandknagaya

## 👏 解決する issue / Resolved Issues
- close #33 

## 📝 関連する issue / Related Issues

## ⛏ 変更内容 / Details of Changes

- 左側メニューの多言語対応

## 📸 スクリーンショット / Screenshots

![#33エビデンス](https://user-images.githubusercontent.com/65159906/107774845-e4660780-6d82-11eb-94e8-1377ecbab92f.JPG)

2021-02-18 02:09 UTC, aktnk commented on assets/locales/en.json
> +  "富士市新型コロナウイルス関連情報": "COVID-19 Related Information in Fuji-shi",
「富士市新型コロナウイスる関連情報」は、
”Information related to COVID19 in Fuji City"あたりが良いかと思います。

2021-02-18 02:10 UTC, aktnk commented on assets/locales/ja-Hira.json
> -  "静岡県内の最新感染動向": "静岡県（しずおかけん）での コロナウイルスの あたらしい じょうほう",
やさしい日本語のみ、「静岡県内の最新感染動向」が無くなっています。

2021-02-18 02:12 UTC, aktnk commented on assets/locales/ja-Hira.json
>    "県内の最新感染動向": "静岡県（しずおかけん）での コロナウイルスの あたらしい じょうほう",
やさしい日本語のみ、「県内の最新感染動向」が存在しています。

2021-02-18 02:14 UTC, aktnk requested changes
@jandknagaya 
いくつかコメントしましたので、確認をお願いします。

2021-02-18 02:30 UTC, jandknagaya commented on assets/locales/en.json
> +  "富士市新型コロナウイルス関連情報": "COVID-19 Related Information in Fuji-shi",
Fuji-shi（←陽性者属性で使ってる表記）と、Fuji City私も悩んだところなんです。
Fuji Cityにします。

2021-02-18 05:04 UTC, aktnk commented on assets/locales/zh_CN.json
> +  "多言語対応選択メニュー": "選擇語言",
東京都、静岡県の対策サイトと合わせて、「选择语言」としましょう。

2021-02-18 05:06 UTC, aktnk requested changes
何度も申し訳ありません。
多言語対応選択メニューの修正をお願いします。

2021-02-18 08:45 UTC, jandknagaya commented
ありがとうございました。
対応しました。

2021-02-21 12:48 UTC, aktnk approved these changes
@jandknagaya さん
遅くなりました。確認完了しました。
問題ありません。

2021-02-21 12:50 UTC, merged